# Generated by Django 4.2 on 2024-10-13 09:15

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=5, max_length=8, prefix='dp', unique=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='spend_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=5, max_length=8, prefix='sp', unique=True),
        ),
    ]
