# Generated by Django 4.2 on 2024-10-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_deposit_deposit_id_alter_spend_spend_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
            ],
        ),
    ]
