# Generated by Django 4.2 on 2024-10-13 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.payment_account'),
        ),
        migrations.AlterField(
            model_name='payment_account',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_account',
            name='account_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='payment_account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
