# Generated by Django 4.2 on 2024-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_deposit_payment_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_account',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
