# Generated by Django 4.2 on 2024-10-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_payment_account_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_account',
            options={'verbose_name': 'Payment Account', 'verbose_name_plural': 'Payment Accounts'},
        ),
    ]
