# Generated by Django 4.2 on 2024-10-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_payment_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.deposit'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='spend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.spend'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.payment_account'),
        ),
    ]
