# Generated by Django 4.2 on 2024-10-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_transactions_deposit_transactions_spend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='spend',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.payment_account'),
        ),
    ]
