# Generated by Django 4.2 on 2025-03-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_subscription_subscriptionplan_remove_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
