# Generated by Django 4.2 on 2025-03-17 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Upload payment receipt', null=True, upload_to='deposits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
