# Generated by Django 4.2 on 2025-05-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_deposit_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('pay_address', models.CharField(max_length=255)),
                ('pay_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('pay_currency', models.CharField(max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WAITING', 'Waiting for Payment'), ('CONFIRMING', 'Confirming Payment'), ('SENDING', 'Sending to Merchant')], default='WAITING', max_length=20)),
                ('ipn_received', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Crypto Payment',
                'verbose_name_plural': 'Crypto Payments',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_type',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('CRYPTO', 'Cryptocurrency')], default='BANK', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WAITING', 'Waiting for Payment'), ('CONFIRMING', 'Confirming Payment'), ('SENDING', 'Sending to Merchant')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WAITING', 'Waiting for Payment'), ('CONFIRMING', 'Confirming Payment'), ('SENDING', 'Sending to Merchant')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='crypto_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.cryptopayment'),
        ),
    ]
