# Generated by Django 4.2 on 2025-05-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_cryptopayment_deposit_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='crypto_payment',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_id',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.AddField(
            model_name='deposit',
            name='ipn_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(blank=True, default='USD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WAITING', 'Waiting for Payment'), ('CONFIRMING', 'Confirming Payment'), ('SENDING', 'Sending to Merchant')], default='WAITING', max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='price_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='CryptoPayment',
        ),
        migrations.DeleteModel(
            name='Payment_account',
        ),
    ]
