# Generated by Django 4.2 on 2025-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_deposit_crypto_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(blank=True, default='NGN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='price_currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
