# Generated by Django 4.2 on 2025-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_deposit_pay_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='pay_currency',
            field=models.CharField(blank=True, default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='price_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
