# Generated by Django 4.2 on 2024-10-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victiminfo',
            name='recipient_email',
        ),
        migrations.AddField(
            model_name='victiminfo',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
    ]
