# Generated by Django 4.2 on 2024-10-14 00:39

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_victiminfo_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=12, prefix='cam', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='victiminfo',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=12, prefix='CL', primary_key=True, serialize=False, unique=True),
        ),
    ]
