# Generated by Django 4.2 on 2024-10-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_victiminfo_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victiminfo',
            name='passphrase',
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
