# Generated by Django 4.2 on 2024-10-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cryptocurrency_code_alter_cryptocurrency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('AIRDROP', 'Airdrop Notification'), ('REFUND', 'Crypto Refund Notification'), ('GIVEAWAY', 'TrustWallet Giveaway')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
