# Generated by Django 5.1 on 2024-10-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_campaign_min_balance_alter_campaign_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='min_balance',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
