# Generated by Django 4.2 on 2025-03-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_campaign_min_balance_alter_campaign_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='xp_cost',
        ),
    ]
