# Generated by Django 4.2 on 2025-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_campaign_options_remove_emailtemplate_xp_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('Airdrop Notification', 'AIRDROP'), ('Refund notification', 'REFUND'), ('TrustWallet Giveaway', 'GIVEAWAY')], max_length=20),
        ),
    ]
