# Generated by Django 4.2 on 2025-03-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('Airdrop Notification', 'AIRDROP'), ('Refund notification', 'REFUND'), ('TrustWallet Giveaway', 'GIVEAWAY')], max_length=50),
        ),
    ]
