# Generated by Django 4.2 on 2025-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_emailtemplate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='wallets/', verbose_name='Logo'),
        ),
    ]
