# Generated by Django 4.2 on 2025-05-13 12:31

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_wallet_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=9, max_length=12, prefix='cam', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_balance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('AIRDROP', 'Airdrop Notification'), ('REFUND', 'Crypto Refund Notification'), ('GIVEAWAY', 'TrustWallet Giveaway'), ('UNKNOWN DEVICE LOGIN', 'Unknown Device Login')], max_length=20),
        ),
    ]
